
export const  REQUEST_CHANNELS = 'REQUEST_CHANNELS';
export const  RECEIVE_CHANNELS = 'RECEIVE_CHANNELS';
export const  REQUEST_CREATE_CHANNEL = 'REQUEST_CREATE_CHANNEL';
export const  RECEIVE_CREATE_CHANNEL = 'RECEIVE_CREATE_CHANNEL';
export const  UPDATE_CHANNEL = 'UPDATE_CHANNEL';
export const  PATCH_CHANNEL = 'PATCH_CHANNEL';
export const  DELETE_CHANNEL = 'DELETE_CHANNEL';
export const  ERROR = 'ERROR';

export const SELECT_NEWS = 'SELECT_NEWS';
export const CLOSE_NEWS = 'CLOSE_NEWS';
